### ISSUE TITLE
HebiCam Java exception

### ISSUE THREAD

**Issue by bsaund** [HebiRobotics/HebiCam#1]
After installing the latest release I get a Java exception when I try to create a HebiCam object.
Ubuntu 14.04

> > cam = HebiCam('http://10.10.10.107/mjpeg');
> > Warning: The following error was caught while
> > executing 'HebiCam' class destructor:
> > Undefined function 'stop' for input arguments of type
> > 'double'. 
> > In cam_rotate (line 25) 
> > Error using HebiCam (line 72)
> > Java exception occurred:
> > java.lang.UnsatisfiedLinkError: no jniopencv_core in
> > java.library.path
> >     at java.lang.ClassLoader.loadLibrary(Unknown
> >         Source)
> >     at java.lang.Runtime.loadLibrary0(Unknown
> >         Source)
> >     at java.lang.System.loadLibrary(Unknown
> >         Source)
> >     at
> >         org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:536)
> >             at
> >         org.bytedeco.javacpp.Loader.load(Loader.java:411)
> >             at
> >         org.bytedeco.javacpp.Loader.load(Loader.java:354)
> >             at
> >         org.bytedeco.javacpp.opencv_core.<clinit>(opencv_core.java:10)
> >             at java.lang.Class.forName0(Native
> >         Method)
> >     at java.lang.Class.forName(Unknown Source)
> >     at
> >         org.bytedeco.javacpp.Loader.load(Loader.java:386)
> >             at
> >         org.bytedeco.javacpp.Loader.load(Loader.java:354)
> >             at
> >         org.bytedeco.javacpp.opencv_core$MatVector.<clinit>(opencv_core.java:225)
> >             at
> >         us.hebi.matlab.streaming.MatlabImageConverter$RgbConverter.<init>(MatlabImageConverter.java:93)
> >             at
> >         us.hebi.matlab.streaming.MatlabImageConverter.createRgbConverter(MatlabImageConverter.java:43)
> >             at
> >         us.hebi.matlab.streaming.BackingHebiCam.<init>(BackingHebiCam.java:282)
> >             at
> >         us.hebi.matlab.streaming.BackingHebiCam.openRemoteUri(BackingHebiCam.java:99)
> >             at
> >         us.hebi.matlab.streaming.BackingHebiCam.open(BackingHebiCam.java:66)
> >         Caused by: java.lang.UnsatisfiedLinkError:
> >         /tmp/javacpp26829475693961/libjniopencv_core.so:
> >         /usr/local/MATLAB/R2016a/bin/glnxa64/../../sys/os/glnxa64/libstdc++.so.6:
> >         version `GLIBCXX_3.4.20' not found (required
> >         by
> >         /tmp/javacpp26829475693961/libopencv_core.so.2.4)
> >             at
> >         java.lang.ClassLoader$NativeLibrary.load(Native
> >         Method)
> >     at java.lang.ClassLoader.loadLibrary1(Unknown
> >         Source)
> >     at java.lang.ClassLoader.loadLibrary0(Unknown
> >         Source)
> >     at java.lang.ClassLoader.loadLibrary(Unknown
> >         Source)
> >     at java.lang.Runtime.load0(Unknown Source)
> >     at java.lang.System.load(Unknown Source)
> >     at
> >         org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:525)
> >             ... 13 more

Error in cam_rotate (line 25)
cam = HebiCam('http://10.10.10.107/mjpeg');

> > version -java

ans =

Java 1.7.0_60-b19 with Oracle Corporation Java HotSpot(TM) 64-Bit Server VM mixed mode

**Comment by ennerf** [comment]
We're using JavaCV, which is a Java wrapper around OpenCV. I've run into issues before where the supplied Linux binaries were compiled using the absolute latest glibc, which resulted in compatibility issues with older versions of Linux.

I'm already using a pretty old version of JavaCV to attempt to mitigate this issue, but I'm not sure what versions of Ubuntu are compatible. Could you try running this on a newer Ubuntu version?

**Comment by ennerf** [comment]
I've updated the JavaCV binaries in release 1.1. I've tested it on Ubuntu 14.04 and 16.04 and this issue seems to be fixed.
