### ISSUE TITLE
Connect to protected IP camera

### ISSUE THREAD

**Issue by BorisTestov** [HebiRobotics/HebiCam#2]
Hello! Is there any way to connect a protected IP camera with HebiCam? I tried 
`cam = HebiCam('adress of my camera','Login','Pass');`, but it doesn't work.

**Comment by ennerf** [comment]
Most cameras have a way to integrate the user/password into the url, e.g., rtsp://user:password@ip-address/ or http://ip-address/video?user=myUser&password=myPassword. You'll need to look at the documentation for your camera to find out the right url.

**Comment by BorisTestov** [comment]
Thanks a lot, it works! But now I have another problem: when I launched programme second time, I got this error:

>Warning: The following error was caught while executing 'HebiCam' class destructor:
Undefined function 'stop' for input arguments of type 'double'. 
In ipc (line 6) 
Error using HebiCam (line 177)
Java exception occurred:
java.lang.IllegalArgumentException: Unsupported number of channels: 0
>	at us.hebi.matlab.streaming.BackgroundFrameGrabber.<init>(BackgroundFrameGrabber.java:63)


Error in ipc (line 6)
cam = HebiCam('rtsp://user:password@ip-adress');

And here is the code:
`clear all;`
`cam = HebiCam('rtsp://user:password@ip-adress');`
`figure();`
`fig = imshow(getsnapshot(cam));`
`while true`
`    set(fig, 'CData', getsnapshot(cam)); `
`    drawnow;`
`end`

First time it worked good, what can be wrong now?

**Comment by ennerf** [comment]
Did you replace "user" "password" and "ip-address" with the correct values for your camera? This looks like the URL is not correct. Can you open the stream in, e.g., VLC?

If this only happens the second time around, your camera may only support 1 stream at a time. You could try:

clear cam;
cam = HebiCam(...);

This stops the first connection before creating a second one.

**Comment by BorisTestov** [comment]
Hmm, I rewrote ip-adress and it works fine now. And the last question: can i get access to speaker or IR backlight on my IP camera?

**Comment by ennerf** [comment]
Not at the moment. The current implementation only supports video. I currently don't have access to cameras with speakers or backlights, so I'm not sure how those are usually accessed.
